# 开发环境配置
server:
  # 服务端口
  port: 19081
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#  ssl:
#    key-store: classpath:XXXX.pfx
#    key-store-password: XXXX
#    key-store-type: PKCS12


# Spring配置
spring:
  application:
    name: quick_start
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:dao/*Dao.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml